[project]
name = 'Remote-Equipment-Insurance-Platform'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.equipment-failure-claims]
path = 'contracts/equipment-failure-claims.clar'
clarity_version = 3
epoch = 'latest'

[contracts.equipment-health-oracle]
path = 'contracts/equipment-health-oracle.clar'
clarity_version = 3
epoch = '3.2'

[contracts.usage-pattern-tracker]
path = 'contracts/usage-pattern-tracker.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
